Reiterate tests

diff --git a/.github/workflows/test-string-secrets.yml b/.github/workflows/test-string-secrets.yml
--- a/.github/workflows/test-string-secrets.yml
+++ b/.github/workflows/test-string-secrets.yml
@@ -6,7 +6,7 @@ on: push
 jobs:
   test-string-compare:
     runs-on: ubuntu-latest
-    container: swiftlang/swift:nightly-5.3-xenial
+    
     env:
       STRING: ${{ secrets.STRING == 'string' }}
     steps:
@@ -16,10 +16,11 @@ jobs:
         run: echo "passes!"
   test-if-expressions:
     runs-on: ubuntu-latest
-    container: swiftlang/swift:nightly-5.3-xenial
+    
     env:
       ENV_VAR_RAW: ${{ secrets.DEPLOY_TO_DEV_ISTRUE_OR_ISFALSE }}
-      ENV_VAR_BOOL: ${{ secrets.DEPLOY_TO_DEV_ISTRUE_OR_ISFALSE == 'istrue' }}
+      ENV_VAR_BOOL_TRUE: ${{ secrets.DEPLOY_TO_DEV_ISTRUE_OR_ISFALSE == 'istrue' }}
+      ENV_VAR_BOOL_FALSE: ${{ secrets.DEPLOY_TO_DEV_ISTRUE_OR_ISFALSE == 'istruebob' }}
     steps:
     - uses: actions/checkout@v2
     - name: test_3
@@ -33,24 +34,62 @@ jobs:
       run: |
         set -x
         echo "true: ${{ true }}"
-        if [ ${{ true }} ]; then
+        
+        if ${{ true }}; then
+          echo "pure true expression"
+        fi
+        if ${{ false }}; then
+          echo "pure false expression"
+        fi
+        if [ ${{ env.ENV_VAR_BOOL_TRUE }} ]; then
           echo "true expression with test"
         fi
-        if ${{ true }}; then
-          echo "true expression"
+        if ${{ env.ENV_VAR_BOOL_TRUE }}; then
+          echo "pure true expression with env result"
+        fi
+        if [ ${{ env.ENV_VAR_BOOL_FALSE }} ]; then
+          echo "false expression with test"
+        fi
+        if ${{ env.ENV_VAR_BOOL_FALSE }}; then
+          echo "pure false expression"
         fi
     - name: test_7
       id: test_7
-      if: ${{ env.ENV_VAR_BOOL }}
-      run: echo "good"
+      if: ${{ env.ENV_VAR_BOOL_TRUE }}
+      run: echo "good"    
+    - name: test_8
+      id: test_8
+      if: ${{ env.ENV_VAR_BOOL_FALSE }}
+      run: echo "bad"
     
-
-  determine-value:
+  test-true:
     runs-on: ubuntu-latest
-    container: swiftlang/swift:nightly-5.3-xenial
+    
     # needs: previous_step which runs the tests...
     env:
-      SHOULD_DEPLOY: ${{ secrets.DEPLOY_TO_DEV_ISTRUE_OR_ISFALSE }}
+      SHOULD_DEPLOY: ${{ secrets.DEPLOY_TO_DEV_ISTRUE_OR_ISFALSE == 'istrue' }}
+    steps:
+    - uses: actions/checkout@v2
+    - name: test_1
+      id: test_1
+      # TODO: Add success(): Returns true when none of the previous steps have failed or been canceled
+      # && if merge pr
+      if: ${{ env.SHOULD_DEPLOY == 'istrue' }}
+      run: | 
+        echo "ran!"
+        if [ $SHOULD_DEPLOY = "istrue" ]; then
+          echo "expression also checks out here"
+        elif [ $SHOULD_DEPLOY = "isfalse" ]; then
+          echo "Does not check out expression" >&2
+        else
+          echo "does not compute" >&2
+        fi
+      shell: bash
+  test-false:
+    runs-on: ubuntu-latest
+    # needs: previous_step which runs the tests...
+    env:
+      SHOULD_DEPLOY: ${{ 'isfalse' }}
     steps:
     - uses: actions/checkout@v2
     - name: test_1
